-
 name: Playbook-1
 hosts: localhost
 tasks:
  - name: Install firewalld
    yum:
      name: firewalld
      state: present

  - name: Start firewalld service
    service:
      name: firewalld
      state: started

  - name: Enable firewalld service
    service:
      name: firewalld
      enabled: yes
      
-
 name: Playbook-2
 hosts: localhost
 tasks:
  - name: Install MariaDB
    yum:
      name: mariadb-server
      state: present
      
  - name: Start mariadb service
    service:
      name: mariadb
      state: started
       
  - name: Enable mariadb
    service:
      name: mariadb
      enabled: yes
      
-
 name: Playbook-3
 hosts: localhost
 tasks:
  - name: Configure Firewall
    firewalld:
      state: enabled
      zone: public
      permanent: true
      port: 3306/tcp
     
      
      
