# notes:
# name = description
# under the name field, is the LINUX COMMAND, e.g. service, yum, mariad, etc. 
-
 name: Playbook-1 Install and configure Firewall
 hosts: localhost
 tasks:
  - name: Install firewalld
    yum:
      name: firewalld
      state: present

  - name: Start firewalld service
    service:
      name: firewalld
      state: started

  - name: Enable firewalld service
    service:
      name: firewalld
      enabled: yes
      
#///////////////////////////////////////////////////////   
-
 name: Playbook-2 Install and configure MariaDB
 hosts: localhost
 tasks:
  - name: Install MariaDB
    yum:
      name: mariadb-server
      state: present
      
  - name: Start mariadb service
    service:
      name: mariadb
      state: started
       
  - name: Enable mariadb
    service:
      name: mariadb
      enabled: yes
      
-
 name: Playbook-3
 hosts: localhost
 tasks:
  - name: Configure Firewall
    firewalld:
      state: enabled
      zone: public
      permanent: true
      port: 3306/tcp
      
  - name: Reload firewalld
    service:
      name: firewalld
      state: reloaded
      
# notes:
# use mysql_db module. 
# must have mysql_python installed.       
-
 name: Playbook-4
 hosts: localhost
 tasks:
  - name: create database ecomdb
    mysql_db:
      name: ecomdb
      state: present    

  - name: Add a user
    mysql_user: 
      name: ecomuser
      password: ecompassword
      priv: '*.*:ALL,GRANT'
      state: present
      
  - name: import sql data
    shell: mysql < db-load-script.sql
    
#///////////////////////////////////////////////////////     
    
-
 name: Playbook-5 Install and configure PHP
 hosts: localhost
 tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
      
  - name: Install php
    yum:
      name: php
      state: present
  - name: Install php-mysql
    yum:
      name: php-mysqlnd
      state: present
      
-
 name: Playbook-6
 hosts: localhost
 tasks:
  - name: Configure Firewall
    firewalld:
      state: enabled
      zone: public
      permanent: true
      port: 80/tcp
      
  - name: Reload firewalld
    service:
      name: firewalld
      state: reloaded 


# Also remember to change the IP address to reflect the IP of the db server.
-
 name: Playbook-7 Configure HTTPD file
 hosts: localhost
 tasks:
  - name: Configure httdp file
    #lineinfile: dest=/etc/httpd/conf/httpd.conf regexp='^index.html' line='index.php'
    replace:
      path: /etc/httpd/conf/httpd.conf
      regexp: 'index.html'
      replace: 'index.php'

  
  - name: start the httpd service 
    service:
      name: httpd
      state: started
      
  - name: enable httpd   
    systemd:
      name: httpd
      enabled: true

-
 name: Playbook-8 Install git
 hosts: localhost
 tasks:
  - name: Install git
    yum:
     name: git
     state: present

  - name: pull git clone
    git:
     repo: 'https://github.com/kodekloudhub/learning-app-ecommerce.git'
     dest:  /var/www/html/
     clone: yes

    
        
     
      
      
