# --------------------------
- name: Play to install and configure IP Asset Manamgement app (IPAM).
  hosts: localhost
  vars:
      PHPpackages:
        - php
        - php-cli
        - php-gd
        - php-common
        - php-ldap
        - php-pdo
        - php-pear
        - php-snmp
        - php-xml
        - php-mysqlnd
        - php-mbstring
        - php-json
        - php-gmp
  become: yes
  become_user: root
  tasks:
    - name: Setting locale
      blockinfile:
        path: /etc/environment
        block: |
          LC_ALL=en_US.utf-8
          LANG=en_US.utf-8
          
    # --------------------------

    - name: Install epel-release repository
      yum:
        name: epel-release
        state: present

    # --------------------------

    - name: Install httpd
      yum:
        name: httpd
        state: present

    # --------------------------

    - name: Install php dependencies
      yum:
        name: "{{ PHPpackages }}"
        state: present

    # --------------------------
    - name: Install git
      yum:
        name: git
        state: present

    # --------------------------
    - name: Install mariadb
      yum:
        name: mariadb-server
        state: present

    # --------------------------
    - name: Configuring and running Apache webserver
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        marker: "{mark}"
        marker_begin: "<Directory \"/var/www/html\">"
        marker_end: "</Directory>"
        block: |
          Options FollowSymLinks
          AllowOverride all
          Order allow,deny
          Allow from all

    # --------------------------

    - name: Set server name to localhost port 80
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "#ServerName www.example.com:80"
        replace: "ServerName locahost:80"

    # --------------------------

    - name: Set correct timezone to php.ini to avoid php warnings
      replace:
        path: /etc/php.ini
        regexp: ";date.timezone ="
        replace: ";date.timezone = America/Chicago"
        
    # --------------------------
    
    - name: start the httpd service 
      service:
        name: httpd
        state: started
        
    - name: enable httpd   
      systemd:
        name: httpd
        enabled: true
     
    # --------------------------     
      
    - name: Stop firewalld service
      service:
        name: firewalld
        state: stopped

    - name: Disable firewalld service
      service:
        name: firewalld
        enabled: no
      
    # --------------------------
    
    - name: start the mariadb service 
      service:
        name: mariadb
        state: started
        
    - name: enable httpd   
      systemd:
        name: mariadb
        enabled: yes
        
    # --------------------------
    
    - name: Install git
      yum:
        name: git
        state: present    
    
    - name: Downloading phpipam installation files
      git:
        repo: https://github.com/phpipam/phpipam.git
        dest: /var/www/html/
        clone: yes
        
    # --------------------------
    
    - name: Change file ownership
      file:
        path: /var/www/html/
        state: directory
        recurse: yes
        owner: apache
        group: apache
        
    - name: Change security Linux context
      sefcontext:
        target: /var/www/html/
        setype: httpd_sys_content_t
        ftype: a
        
    - name: Change permissions for the files.
      file:
        path: /var/www/html/
        mode: a-x
        state: directory
        recurse: yes
        
    - name: Change permissions for the directories
      file:
        path: /var/www/html/
        mode: u=rwX,g-rX,o-rX
        state: directory
        recurse: yes
        
    - name: Change security Linux context
      sefcontext:
        target: app/admin/import-export/upload/
        setype: httpd_sys_rw_content_t
        ftype: a
        
    - name: Change security Linux context
      sefcontext:
        target: aapp/subnets/import-subnet/upload/
        setype: httpd_sys_rw_content_t
        ftype: a
        
    - name: Change security Linux context
      sefcontext:
        target: css/1.4.2/images/logo/
        setype: httpd_sys_rw_content_t
        ftype: a
        
    # --------------------------
    
    - name: copy over sample config file to config.php that phpipam uses
      copy:
        src: /var/www/html/config.dist.php
        dest: /var/www/html/config.php
    
    
    
  
